### PR TITLE
Update 1.9.1 downloads

### PR DESCRIPTION
**Pull request by ScottBailey**
# Changes

Changes:
- Update version from `1.5.1` to `1.9.1`.
- mxnet moved it's 3rdparty libs from source into git submodules. We
  work around this by getting the archive commits from github.
- Ensure a modern compiler standard (c++14) is selected via patching.

# Jira

https://anaconda.atlassian.net/browse/PKG-250

# Review Information

## Source

https://github.com/apache/incubator-mxnet/tree/1.9.1

## License

Apache-2

https://github.com/apache/incubator-mxnet/blob/1.9.1/LICENSE

## Upstream Changes

Releases from 1.5.1 to 1.9.1:

https://github.com/apache/incubator-mxnet/releases

## Issues

https://github.com/apache/incubator-mxnet/issues

## Pins and Requireds

https://github.com/apache/incubator-mxnet/blob/1.9.1/python/setup.py#L33
graphviz is removed (made optional) via patching.

## Testing

No special testing has been performed.

# Closing Comments

This needs a very careful review to ensure it's correct.

### CODE REVIEW

**Review by varlackc — COMMENTED** [review]
We need to add the `home url`, `dev_url`, `doc_url`, `summary` and `description` on the different about sections.

https://github.com/AnacondaRecipes/mxnet-feedstock/blob/88577e1cce7d8951c4784c0fb63aadd64a51b696/recipe/meta.yaml#L125&L128

https://github.com/AnacondaRecipes/mxnet-feedstock/blob/88577e1cce7d8951c4784c0fb63aadd64a51b696/recipe/meta.yaml#L261&L264

https://github.com/AnacondaRecipes/mxnet-feedstock/blob/88577e1cce7d8951c4784c0fb63aadd64a51b696/recipe/meta.yaml#L276&L279

https://github.com/AnacondaRecipes/mxnet-feedstock/blob/88577e1cce7d8951c4784c0fb63aadd64a51b696/recipe/meta.yaml#L293&L297

We might need to get the package to build on `osx-64` and `osx-arm64`

**Comment by ScottBailey** [comment]
1.5.1 still builds (see https://github.com/AnacondaRecipes/mxnet-feedstock/pull/14), so this is not a problem on the builder.

Here's a PR for testing hacks: https://github.com/AnacondaRecipes/mxnet-feedstock/pull/12

**Comment by katietz** [comment]
just building s390x directly on builder ...  CI build got stuck without any meaningful error-message :/

**Review by varlackc — APPROVED** [review]
LGTM

**Review by katietz — APPROVED** [review]

**Pull request merged**
